version: "3.5"

services:
    catfactsbackend:
        restart: always
        container_name: catfactsapi
        build:
            context: FlaskAPI
        ports:
            - 5000:5000
        volumes:
            - ./FlaskAPI/:/app/
        networks:
            - catfacts
    catfactsapp:
        container_name: catfactsapp
        restart: always
        build:
            context: FrontEnd
        command: ng serve --host 0.0.0.0 --disableHostCheck true
        ports:
            - "4200:4200"
        networks:
            - catfacts
        depends_on:
            - catfactsbackend
        tty: true
        
networks:
    catfacts:
            driver: "bridge"