version: "2"

services:
    backend:
        restart: always
        container_name: catfactsapi
        build:
            context: FlaskAPI
        ports:
            - 5000:5000
        volumes:
            - ./FlaskAPI/:/app/
        networks:
            - catfacts
networks:
    catfacts:
            driver: "bridge"